name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v1
      with:
        login-server: registerymine.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t registerymine.azurecr.io/newapp:${{ github.sha }}
        docker push registerymine.azurecr.io/newapp:${{ github.sha }}
